---
title: "Clustering Assignment#4"
author: "Ran Dou, Mduduzi Langwenya, Kimo Li, Siyan Lin, Muhammad Furqan Shaikh, Tianyi Zhou"
date: "03/25/2019"
output: html_document
---

load all libraries

```{r}
library(cluster)
library(tidyverse)
library(NbClust)
library(factoextra)
library(clValid)
library(writexl)
```

### I. Data cleaning and impution

##### Data importing
```{r, warning=FALSE, message=FALSE}
###import the raw diabetes data
diabetes <- read_csv("diabetes.csv")
###delete all the missing valuse
diabetes1 <- diabetes %>%
  filter( Glucose !=0 & BMI != 0 & BloodPressure != 0 & Insulin != 0 & SkinThickness != 0) %>%
  select(Glucose, Insulin, Outcome, BMI, SkinThickness )
```

##### Fill-in Zero Value
###### 1) Insulin
```{r,message=FALSE,  echo=T, results='hide'}
### Insulin 
# stepwise for choosing models for Insulin 
insu.lm.null <- lm(Insulin~1, data = diabetes1)
insu.lm <- lm(Insulin~., data = diabetes1)
insu.lm.step_both <- step(insu.lm, direction = "both")
sum_both <- summary(insu.lm.step_both)
### create the model for imputing Insulin missing values
lm.data <- lm (Insulin ~ Glucose + BMI, data=diabetes1)
pred.1 <- predict (lm.data, diabetes1)
impute <-function(a, a.impute){
         ifelse(a$Insulin == 0, round(a.impute, 0), a$Insulin)
}
diabetes$newInsu <- impute(diabetes, pred.1)
rm( insu.lm, insu.lm.null, insu.lm.step_both, sum_both, lm.data)
```

###### 2) Skinthickness 
```{r}
### stepwise for choosing models for Insulin 
skin.lm.null <- lm(SkinThickness~1, data = diabetes1)
skin.lm <- lm(SkinThickness~., data = diabetes1)
skin.lm.step_both <- step(skin.lm, direction = "both")
sum_both_skin <- summary(skin.lm.step_both)
### create the model for imputing SkinThickness missing values
lm2.data <- lm(SkinThickness ~ BMI, data=diabetes1)
pred.2 <- predict (lm2.data, diabetes1)
impute <-function(a, a.impute){
  ifelse(a$SkinThickness == 0, round(a.impute, 0), a$SkinThickness)
}
diabetes$newSkin <- impute(diabetes, pred.2)

rm(skin.lm.null, skin.lm, skin.lm.step_both, sum_both_skin, lm2.data, pred.2,diabetes1, impute, pred.1)

diabetes$SkinThickness <- NULL
diabetes$Insulin <- NULL

diabetes <- diabetes %>%
  rename(Insulin = "newInsu",
         SkinThickness = "newSkin")

diabetes<- as_tibble(diabetes)
diabetes.copy<-diabetes

```


K-Means Clustering

1. Scaling 

```{r}
summary(diabetes)
# ==========
dia.df.num = model.matrix(~ Pregnancies + Glucose + BMI + DiabetesPedigreeFunction +
                            Age + BloodPressure + SkinThickness + Insulin + 
                            + factor(Outcome),  data = diabetes)

scaled_data = scale(dia.df.num[,-1])

```

2. Choose Number of Clusters- Use Within Sum of Squares (wss)
```{r}
## How many clusters to choose?
## ============================
k.max <- 15
wss <- sapply(1:k.max, 
              function(k){kmeans(diabetes$Glucose, k, nstart=50,iter.max = 20 )$tot.withinss})
wss

plot(1:k.max, wss,
     type="b", pch = 19, frame = FALSE, 
     xlab="Number of clusters K",
     ylab="Total within-clusters sum of squares")

```


3. K-Means Clustering - I chose 3 Groups

```{r}

# Find 2  groups
# ==========        # because starting assignments are random
dia.k3 <- kmeans(diabetes , centers=3, nstart = 50, iter.max = 20 )

#add cluster back to dataframe
diabetes$cluster <- dia.k3$cluster

table(diabetes$Insulin, diabetes$cluster)

```

# plotting 

```{r}
#plot glucose and BMI
ggplot(diabetes, aes(Insulin, Insulin, col = factor(cluster))) + 
  geom_point(stat = "identity")
```

```{r}

#plot glucose and pregnancies
ggplot(diabetes, aes(Glucose, Insulin, col = factor(cluster))) + 
  geom_point(stat = "identity")

```

```{r}
#plot blood pressue and insulin
ggplot(diabetes, aes(BloodPressure, Insulin, col = factor(cluster))) + 
  geom_point(stat = "identity")
```



```{r}
#plot  Age and insulin
ggplot(diabetes, aes(Age, Insulin, col = factor(cluster))) + 
  geom_point(stat = "identity")
```

```{r}
#plot BMI and insulin
ggplot(diabetes, aes(BMI, Insulin, col = factor(cluster))) + 
  geom_point(stat = "identity")

```

Hcluster
```{r}
diabetes<-diabetes.copy
# delete outcome. take glucose as target
diabetes <- diabetes%>% select(-"Outcome")

# normalize input variables
diabetes.df.norm <- sapply(diabetes, scale)

# add row names: 
row.names(diabetes.df.norm) <- row.names(diabetes) 
d.norm <- dist(diabetes.df.norm, method = "euclidean")  

# in hclust() set argument method =  
# to "ward.D", "single", "complete", "average", "median", or "centroid",  246 work
hc1 <- hclust(d.norm, method = "single")
plot(hc1, main = "Single Linkage Clustering", hang = -1, labels=FALSE)

hc2 <- hclust(d.norm, method = "average")
plot(hc2, main = "Average Linkage Clustering", hang = -1, labels=FALSE)

hc3 <- hclust(d.norm, method = "median")
plot(hc3, main = "Median Linkage Clustering", hang = -1, labels=FALSE)

hc4 <- hclust(d.norm, method = "complete")
plot(hc4, main = "Complete Linkage Clustering", hang = -1, labels=FALSE)

hc5 <- hclust(d.norm, method = "centroid")
plot(hc5, main = "Centroid Linkage Clustering", hang = -1, labels=FALSE)

hc6 <- hclust(d.norm, method = "ward.D")
plot(hc6, main = "Ward.D Linkage Clustering", hang = -1, labels=FALSE)
```
###compare and choose best clustering model with linkage and k
```{r}
single=rep(0,6)
for (i in 1:15)
{memb1<-cutree(hc1,k=i)
single[i]=dunn(d.norm,memb1)}

average=rep(0,6)
for (i in 1:15)
{memb2<-cutree(hc2,k=i)
average[i]=dunn(d.norm,memb2)}

median=rep(0,6)
for (i in 1:15)
{memb3<-cutree(hc3,k=i)
median[i]=dunn(d.norm,memb3)}

complete=rep(0,6)
for (i in 1:15)
{memb4<-cutree(hc4,k=i)
complete[i]=dunn(d.norm,memb4)}

centroid=rep(0,6)
for (i in 1:15)
{memb5<-cutree(hc5,k=i)
centroid[i]=dunn(d.norm,memb5)}

ward.D=rep(0,15)
for (i in 1:15)
{memb6<-cutree(hc6,k=i)
ward.D[i]=dunn(d.norm,memb6)}

library(knitr)
dun<-data.frame(single,average,median,complete,centroid,ward.D) %>%round(2) 
k<-(1:15)
dunn_result<-cbind(k,dun)
library(writexl)
write_xlsx(x = dunn_result, path = "dunn_result.xlsx", col_names = TRUE)
```

####plot the histogram of clusters to decide the k
```{r}
# ward clusters are more evenly 


for (i in 1:3)
{memb2<-cutree(hc2,k=i)
hist(memb2)}

memb2<-cutree(hc2,k=2)
hist(memb2)

for (i in 1:3)
{memb4<-cutree(hc4,k=i)
hist(memb4)}

memb4<-cutree(hc4,k=2)
hist(memb4)

for (i in 1:3)
{memb6<-cutree(hc6,k=i)
hist(memb6)}

memb6<-cutree(hc6,k=2)
hist(memb6)

```


```{r}
# trees of method average, complete, ward.d are more clear, so we take those three
# different colors refer to different clusters
#head(colors()) 
# fviz_dend(hc2, k = 13, 
#           cex = 0.5, 
#           k_colors = c("#2E9FDF", "#00AFBB", "#E7B800", "#FC4E07", "#A52A2A","#FF4040","#EE3B3B","#8B2323","#CDAA7D","#98F5FF","#7FFF00","#66CD00","#53868B"),
#           color_labels_by_k = TRUE, 
#           rect = TRUE          
# )
# 
# fviz_dend(hc4, k = 8, 
#           cex = 0.5, 
#           k_colors = c("#2E9FDF", "#00AFBB", "#E7B800", "#FC4E07", "#A52A2A","#FF4040","#EE3B3B","#8B2323"),
#           color_labels_by_k = TRUE, 
#           rect = TRUE          
# )

fviz_dend(hc6, k = 2, 
          cex = 0.5, 
          k_colors = c("#2E9FDF", "#00AFBB"),
          color_labels_by_k = TRUE, 
          rect = TRUE          
)
```




```{r}
# # get cluster number
# average <- cutree(hc2, k = 13)
# dunn(d.norm, average)
# #memb2
# complete <- cutree(hc4, k = 8)
# dunn(d.norm, complete)
# #memb4
# Ward <- cutree(hc6, k = 10)
# dunn(d.norm, Ward)
# #memb6
```

```{r}
#get histogram for clusters
cat(memb2)
cat(memb4)
cat(memb6)

hist(average)
hist(complete)
hist(Ward)
```

```{r}
# get heatmaps for three methods

row.names(diabetes.df.norm) <- paste(memb2, ": ", row.names(diabetes), sep = "")

# plot heatmap 
# rev() reverses the color mapping to large = dark
heatmap(as.matrix(diabetes.df.norm), Colv = NA, hclustfun = hclust, 
        col=rev(paste("grey",1:99,sep="")))

# set labels as cluster membership number : utility name
row.names(diabetes.df.norm) <- paste(memb4, ": ", row.names(diabetes), sep = "")

# plot heatmap 
# rev() reverses the color mapping to large = dark
heatmap(as.matrix(diabetes.df.norm), Colv = NA, hclustfun = hclust, 
        col=rev(paste("grey",1:99,sep="")))

# set labels as cluster membership number : utility name
row.names(diabetes.df.norm) <- paste(memb6, ": ", row.names(diabetes), sep = "")

# plot heatmap 
# rev() reverses the color mapping to large = dark
heatmap(as.matrix(diabetes.df.norm), Colv = NA, hclustfun = hclust, 
        col=rev(paste("grey",1:99,sep="")))

```

```{r}
# new dataset with cluster results
diabetes_new <- diabetes.copy %>% mutate(HierCluster=memb6)

# Create theme for plots
theme <- theme_test(base_family = "Times New Roman") + theme(plot.title = element_text(hjust = 0.5), 
         legend.position = "bottom", panel.grid.minor = element_blank(), axis.ticks.x = element_blank(),
         axis.ticks.y = element_blank(), panel.grid.major = element_blank())
```

```{r}
str(diabetes_new)
# get boxplot of glucose for different clusters with three methods
##Glucose
ggplot(diabetes_new, aes(x = as.factor(HierCluster), y = Glucose   )) +
  geom_boxplot(colour = "black") +
  theme + labs(title = "Distribution of Glucose by cluster ", x = "cluster", y = "Glucose")
#BMI
ggplot(diabetes_new, aes(x = as.factor(HierCluster), y = BMI   )) +
  geom_boxplot(colour = "black") +
  theme + labs(title = "Distribution of BMI by cluster ", x = "cluster", y = "BMI")

#age
ggplot(diabetes_new, aes(x = as.factor(HierCluster), y = Age  )) +
  geom_boxplot(colour = "black") +
  theme + labs(title = "Distribution of age by cluster ", x = "cluster", y = "Age")

#DiabetesPedigreeFunction
ggplot(diabetes_new, aes(x = as.factor(HierCluster), y = DiabetesPedigreeFunction  )) +
  geom_boxplot(colour = "black") +
  theme + labs(title = "Distribution of DiabetesPedigreeFunction by cluster ", x = "cluster", y = "DiabetesPedigreeFunction")

#BloodPressure
ggplot(diabetes_new, aes(x = as.factor(HierCluster), y = BloodPressure  )) +
  geom_boxplot(colour = "black") +
  theme + labs(title = "Distribution of BloodPressure by cluster ", x = "cluster", y = "BloodPressure")

#Insulin
ggplot(diabetes_new, aes(x = as.factor(HierCluster), y =Insulin  )) +
  geom_boxplot(colour = "black") +
  theme + labs(title = "Distribution of Insulin by cluster ", x = "cluster", y = "Insulin")

# ggplot(diabetes_new, aes(x = as.factor(HierCluster2), y = Glucose)) +
#   geom_boxplot(colour = "black") +
#   theme + labs(title = "Distribution of Glucose by cluster of complete method", x = "cluster", y = "Glucose")
# 
# ggplot(diabetes_new, aes(x = as.factor(HierCluster3), y = Glucose)) +
#   geom_boxplot(colour = "black") +
#   theme + labs(title = "Distribution of Glucose by cluster of ward method", x = "cluster", y = "Glucose")

cluster_outcome<-diabetes_new %>% group_by(HierCluster,Outcome) %>% summarise(n=n())
write_xlsx(cluster_outcome, path =  "cluster_outcome.xlsx",col_names = TRUE,
  format_headers = TRUE)

#Outcome ~ Glucose +  BMI + Age+DiabetesPedigreeFunction + BloodPressure 

```


```{r}
#plot BMI and glucose
ggplot(diabetes_new, aes(BMI, Glucose, col = factor(HierCluster))) + 
  geom_point(stat = "identity")+theme
```

```{r}
#plot Age and glucose
ggplot(diabetes_new, aes(Age, Glucose, col = factor(HierCluster))) + 
  geom_point(stat = "identity")+theme
```
```{r}
#DiabetesPedigreeFunction and glucose
ggplot(diabetes_new, aes(DiabetesPedigreeFunction, Glucose, col = factor(HierCluster))) + 
  geom_point(stat = "identity")+theme
```


```{r}
#plot insulin and glucose
ggplot(diabetes_new, aes(Insulin, Glucose, col = factor(HierCluster))) + 
  geom_point(stat = "identity")+theme
```


```{r}
#plot BloodPressure and glucose
ggplot(diabetes_new, aes(BloodPressure, Glucose, col = factor(HierCluster))) + 
  geom_point(stat = "identity")+theme
```
